services:
  script-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    #le service S1 qui exécute les scripts s'exécute après le démarrage du service qui stocke les données
    depends_on:
      - sqlite-db
    command: python /app/sales-analyze.py # Au démarrage du conteneur, le script d'analyze des ventes s'exécutera
  sqlite-db:
    image: nouchka/sqlite3:latest
    stdin_open: true         # permet d’ouvrir une session interactive
    tty: true                # permet une interface interactive aussi
    volumes:
      - sqlite-data:/data
    

volumes:
  sqlite-data:
    name: sqlite-data