services:
  script-runner:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./scripts:/app/scripts
    depends_on:
      - sqlite-db
    command: python /app/scripts/monscript.py

  sqlite-db:
    image: nouchka/sqlite3:latest
    command: sqlite3 /data/db.sqlite3
    volumes:
      - sqlite-data:/data
    

volumes:
  sqlite-data:
    name: sqlite-data